# -*- coding: utf-8 -*-
"""garbage_classifier_a2.ipynb

Automatically generated by Colab.

# Garbage Classification (Multimodal: Image + Text)
This notebook trains and evaluates a **multimodal** classifier using:
- **Image**: ResNet-18 backbone
- **Text**: DistilBERT encoder
- **Fusion**: concatenation of embeddings → MLP → 4-way classification

Dataset layout (TALC):
```
garbage_data/
  CVPR_2024_dataset_Train/{Black,Blue,Green,TTR}/*.jpg
  CVPR_2024_dataset_Val/{Black,Blue,Green,TTR}/*.jpg
  CVPR_2024_dataset_Test/{Black,Blue,Green,TTR}/*.jpg
```
"""

#from google.colab import drive
#drive.mount('/content/drive/')

"""## 1. Setup"""

# Standard library imports
import os
import re
import random
from dataclasses import dataclass
from typing import List, Dict, Tuple

# Deep learning setup
import numpy as np
import torch
import torch.nn as nn
from torch.utils.data import Dataset, DataLoader

# Image handling
from PIL import Image
from torchvision import transforms, models

# Text models
from transformers import DistilBertModel, DistilBertTokenizerFast
from tqdm import tqdm

# Evaluation and plotting
from sklearn.metrics import classification_report, confusion_matrix
import matplotlib
matplotlib.use('Agg')  # headless backend for TALC
import matplotlib.pyplot as plt

"""## 2. Config

"""

# Using a dataclass to cleanly store hyperparameters and paths
# to keep organizationa and help make tuning easier

@dataclass
class Config:
  # Dataset locations
  train_path: str
  val_path: str
  test_path: str

  # Training parameters
  img_size: int = 224 # Image resolution (ResNet default is 224x224)
  max_len: int = 150 # Max token length for BERT input
  batch_size: int = 16
  epochs: int = 5
  lr: float = 2e-4 # Learning rate
  weight_decay: float = 1e-4
  num_workers: int = 2

  # Transfer learning technique(prevent overfitting)
  freeze_resnet: bool = True

  # Compute device preference
  device: str = "cuda"

# If CUDA is available use GPU, otherwise fallback to CPU
def get_device(preferred="cuda"):
    return torch.device("cuda" if preferred == "cuda" and torch.cuda.is_available() else "cpu")

# Config to TALC
cfg = Config(
    train_path="/work/TALC/ensf617_2026w/garbage_data/CVPR_2024_dataset_Train",
    val_path="/work/TALC/ensf617_2026w/garbage_data/CVPR_2024_dataset_Val",
    test_path="/work/TALC/ensf617_2026w/garbage_data/CVPR_2024_dataset_Test",
    epochs=5,
    batch_size=16,
)

# Config to drive dataset for testing purposes (Colab) 
# cfg = Config(
#     train_path="/content/drive/MyDrive/CVPR_2024_dataset_Train",
#     val_path="/content/drive/MyDrive/CVPR_2024_dataset_Val",
#     test_path="/content/drive/MyDrive/CVPR_2024_dataset_Test",
# )

device = get_device(cfg.device)
print("Device:", device)

"""## 3. Utilities"""

# Setting all random seeds to ensure reproducibility
def set_seed(seed: int = 42):
  random.seed(seed)
  np.random.seed(seed)
  torch.manual_seed(seed)
  torch.cuda.manual_seed_all(seed)

set_seed(42)

# Convert the filename to text and clean text
def filename_to_text(file_name: str) -> str:
  """Convert `greasy_pizza_box.jpg` -> 'greasy pizza box' (and strip digits)."""
  stem = os.path.splitext(os.path.basename(file_name))[0]
  text = stem.replace("_", " ")
  text = re.sub(r"\d+", "", text)
  return text.strip()

# Detecting class folders automatically to get label
def list_class_folders(split_path: str) -> List[str]:
  """Detect class folders dynamically (e.g., Black/Blue/Green/TTR)."""
  classes = sorted([
    d for d in os.listdir(split_path)
    if os.path.isdir(os.path.join(split_path, d))
  ])
  if len(classes) == 0:
    raise RuntimeError(f"No class folders found in: {split_path}")
  return classes

# Make sure we only load valid image formats
def is_image_file(fn: str) -> bool:
  return fn.lower().endswith((".jpg", ".jpeg", ".png", ".webp", ".bmp", ".tif", ".tiff"))

"""## 4. Dataset
Loads images from folder structure and tokenizes text derived from filenames.
"""

# Load images, extract text from file name, tokenize text
# return everthing together

class MultimodalDataset(Dataset):
  def __init__(self, split_path: str, tokenizer, max_len: int, img_transform):
    self.split_path = split_path # Path to train val test foler
    self.tokenizer = tokenizer # BERT tokenizer
    self.max_len = max_len # Max token length
    self.img_transform = img_transform # Torchvision transforms

    self.class_names = list_class_folders(split_path) # Detect class names
    self.label_map = {cls: i for i, cls in enumerate(self.class_names)} # Map class names to int
    self.idx_to_label = {i: cls for cls, i in self.label_map.items()} # Reverse map for later visualization

    # Store (filepath, label). Walk through each class folder
    self.samples: List[Tuple[str, int]] = []
    for cls in self.class_names:
      cls_dir = os.path.join(split_path, cls)
      for fn in os.listdir(cls_dir):
        fp = os.path.join(cls_dir, fn)
        if os.path.isfile(fp) and is_image_file(fn):
          self.samples.append((fp, self.label_map[cls]))

    if len(self.samples) == 0:
      raise RuntimeError(f"No images found under: {split_path}")

  # Number of samples in dataset
  def __len__(self):
    return len(self.samples)

  # Returns one training example
  def __getitem__(self, idx: int):
    fp, label = self.samples[idx]
    fn = os.path.basename(fp)

    # Image
    img = Image.open(fp).convert("RGB")
    img = self.img_transform(img)

    # Text derived from filename
    text = filename_to_text(fn)

    enc = self.tokenizer(
        text,
        add_special_tokens=True,
        max_length=self.max_len,
        padding="max_length",
        truncation=True,
        return_attention_mask=True,
        return_tensors="pt",
    )

    return {
        "image": img,
        "input_ids": enc["input_ids"].squeeze(0),
        "attention_mask": enc["attention_mask"].squeeze(0),
        "label": torch.tensor(label, dtype=torch.long),
        "text": text,
        "filename": fn,
        "path": fp,
    }

"""## 5. Transforms + DataLoaders"""

# Load pretrained tokenizer
tokenizer = DistilBertTokenizerFast.from_pretrained("distilbert-base-uncased")

# Training transforms including data augmentation
train_tf = transforms.Compose([
    transforms.Resize((cfg.img_size, cfg.img_size)),
    transforms.RandomHorizontalFlip(),
    transforms.RandomVerticalFlip(),
    transforms.ColorJitter(brightness=0.2, contrast=0.2, saturation=0.2),
    transforms.ToTensor(),
    transforms.Normalize(mean=[0.485,0.456,0.406], std=[0.229,0.224,0.225]),
])

# Validation and test transformers (NO augmentation)
eval_tf = transforms.Compose([
    transforms.Resize((cfg.img_size, cfg.img_size)),
    transforms.ToTensor(),
    transforms.Normalize(mean=[0.485,0.456,0.406], std=[0.229,0.224,0.225]),
])

train_ds = MultimodalDataset(cfg.train_path, tokenizer, cfg.max_len, train_tf)
val_ds   = MultimodalDataset(cfg.val_path,   tokenizer, cfg.max_len, eval_tf)
test_ds  = MultimodalDataset(cfg.test_path,  tokenizer, cfg.max_len, eval_tf)



# Use train_ds class order for display
class_names = train_ds.class_names
print("Detected classes:", class_names)

train_loader = DataLoader(train_ds, batch_size=cfg.batch_size, shuffle=True, num_workers=cfg.num_workers)
val_loader   = DataLoader(val_ds, batch_size=cfg.batch_size, shuffle=False, num_workers=cfg.num_workers)
test_loader  = DataLoader(test_ds, batch_size=cfg.batch_size, shuffle=False, num_workers=cfg.num_workers)

print("Train/Val/Test sizes:", len(train_ds), len(val_ds), len(test_ds))



"""## 6. Model (ResNet18 + DistilBERT + Fusion Head)"""

class MultimodalClassifier(nn.Module):
  def __init__(self, num_classes: int, freeze_resnet: bool = True, fusion_hidden: int = 256):
    super().__init__()

    # Image encoder: ResNet-18
    self.resnet = models.resnet18(pretrained=True)
    img_dim = self.resnet.fc.in_features # Get dimension before classification layer
    self.resnet.fc = nn.Identity() # remove final classifier

    # Freeze weights if set
    if freeze_resnet:
      for p in self.resnet.parameters():
        p.requires_grad = False

    # Text encoder: DistilBERT
    self.bert = DistilBertModel.from_pretrained("distilbert-base-uncased")
    txt_dim = self.bert.config.hidden_size

    # Fusion classifier
    self.head = nn.Sequential(
        nn.Linear(img_dim + txt_dim, fusion_hidden),
        nn.ReLU(),
        nn.Dropout(0.2),
        nn.Linear(fusion_hidden, num_classes),
    )

  def forward(self, image, input_ids, attention_mask):
    # Extract image features
    img_feat = self.resnet(image)  # (B, img_dim)

    # Extract text features
    bert_out = self.bert(input_ids=input_ids, attention_mask=attention_mask)
    txt_feat = bert_out.last_hidden_state[:, 0, :]  # (B, txt_dim)

    # Concatenate image and text
    z = torch.cat([img_feat, txt_feat], dim=1)
    return self.head(z)

model = MultimodalClassifier(num_classes=len(class_names), freeze_resnet=cfg.freeze_resnet).to(device)
print(model)

"""## 7. Train / Eval helpers"""

# One full pass over the training DataLoader
# Training loop for standard PyTorch
# Zero gradients, forward, compute loss, backward, update
def train_one_epoch(model, loader, optimizer, criterion, device):
    model.train()
    total_loss = 0.0

    for batch in tqdm(loader, desc="train", leave=False):
        # move tensors to device
        images = batch["image"].to(device)
        input_ids = batch["input_ids"].to(device)
        attention_mask = batch["attention_mask"].to(device)
        labels = batch["label"].to(device)

        optimizer.zero_grad(set_to_none=True) # Clear gradients
        logits = model(images, input_ids, attention_mask) # Forward pass
        loss = criterion(logits, labels) # Loss computation
        loss.backward() # Backward pass
        optimizer.step() # Parameter update

        total_loss += loss.item()

    # return average loss per batch
    return total_loss / max(len(loader), 1) # prevent divide by zero

# One full pass over validation DataLoader
@torch.no_grad()
def eval_one_epoch(model, loader, criterion, device):
    model.eval()
    total_loss = 0.0
    correct = 0
    total = 0

    for batch in tqdm(loader, desc="eval", leave=False):
        images = batch["image"].to(device)
        input_ids = batch["input_ids"].to(device)
        attention_mask = batch["attention_mask"].to(device)
        labels = batch["label"].to(device)

        logits = model(images, input_ids, attention_mask) # Forward pass only for eval
        loss = criterion(logits, labels)
        total_loss += loss.item()

        # Return average loss and accuracy
        # Accuracy = correct predictions over total predictions
        preds = torch.argmax(logits, dim=1)
        correct += (preds == labels).sum().item()
        total += labels.size(0)

    avg_loss = total_loss / max(len(loader), 1)
    acc = correct / max(total, 1)
    return avg_loss, acc

# Predict helper for test set evaluation and metadata
@torch.no_grad()
def predict(model, loader, device):
    model.eval()
    preds_all = []
    labels_all = []
    paths_all = []
    texts_all = []

    for batch in tqdm(loader, desc="predict", leave=False):
        images = batch["image"].to(device)
        input_ids = batch["input_ids"].to(device)
        attention_mask = batch["attention_mask"].to(device)

        logits = model(images, input_ids, attention_mask)
        preds = torch.argmax(logits, dim=1).cpu().numpy()

        preds_all.extend(preds.tolist())
        labels_all.extend(batch["label"].numpy().tolist())
        paths_all.extend(batch["path"])
        texts_all.extend(batch["text"])

    return np.array(preds_all), np.array(labels_all), paths_all, texts_all

"""## 8. Training loop (save best model by validation loss)"""

criterion = nn.CrossEntropyLoss()
optimizer = torch.optim.AdamW(model.parameters(), lr=cfg.lr, weight_decay=cfg.weight_decay)

best_val_loss = float("inf")
best_path = "best_multimodal.pth"

# ---- Output directory (TALC/headless friendly) ----
OUT_DIR = "outputs"
os.makedirs(OUT_DIR, exist_ok=True)

# Save best checkpoint into outputs/
best_path = os.path.join(OUT_DIR, best_path)

def save_history_csv(history_dict, out_path):
    """Save training history for later plotting in eval.ipynb"""
    import csv
    with open(out_path, "w", newline="", encoding="utf-8") as f:
        w = csv.writer(f)
        w.writerow(["epoch", "train_loss", "val_loss", "val_acc"]) # header row
        for i in range(len(history_dict["train_loss"])):
            w.writerow([i + 1, history_dict["train_loss"][i], history_dict["val_loss"][i], history_dict["val_acc"][i]])

history = {"train_loss": [], "val_loss": [], "val_acc": []} # Save for curves

for epoch in range(cfg.epochs):
    tr_loss = train_one_epoch(model, train_loader, optimizer, criterion, device)
    val_loss, val_acc = eval_one_epoch(model, val_loader, criterion, device)

    history["train_loss"].append(tr_loss)
    history["val_loss"].append(val_loss)
    history["val_acc"].append(val_acc)

    print(f"Epoch {epoch+1}/{cfg.epochs} | train_loss={tr_loss:.4f} | val_loss={val_loss:.4f} | val_acc={val_acc:.4f}")

    if val_loss < best_val_loss:
        best_val_loss = val_loss
        torch.save(model.state_dict(), best_path)
        print("Saved best checkpoint:", best_path)

print("Best val loss:", best_val_loss)

"""## 9. Plot training curves"""

# Loss Curve
plt.figure()
plt.plot(history["train_loss"], label="train_loss")
plt.plot(history["val_loss"], label="val_loss")
plt.xlabel("epoch")
plt.ylabel("loss")
plt.title("Loss Curves")
plt.legend()
plt.tight_layout()
plt.savefig(os.path.join(OUT_DIR, "loss_curves.png"), dpi=200)
plt.close()

# Validation Accuracy Curve
plt.figure()
plt.plot(history["val_acc"], label="val_acc")
plt.xlabel("epoch")
plt.ylabel("accuracy")
plt.title("Validation Accuracy")
plt.legend()
plt.tight_layout()
plt.savefig(os.path.join(OUT_DIR, "val_accuracy.png"), dpi=200)
plt.close()

"""## 10. Test evaluation + confusion matrix + classification report"""

model.load_state_dict(torch.load(best_path, map_location=device))

preds, labels, paths, texts = predict(model, test_loader, device)

# Save predictions for eval.ipynb
import csv
with open(os.path.join(OUT_DIR, 'test_predictions.csv'), 'w', newline='', encoding='utf-8') as f:
    w = csv.writer(f)
    w.writerow(['path','text','true','pred','true_name','pred_name'])
    for pth, txt, y, p in zip(paths, texts, labels.tolist(), preds.tolist()):
        w.writerow([pth, txt, y, p, class_names[y], class_names[p]])

test_acc = (preds == labels).mean()
print('Test accuracy:', test_acc)

print('\nClassification report:')
print(classification_report(labels, preds, target_names=class_names, digits=4))

cm = confusion_matrix(labels, preds)
# Save artifacts for eval.ipynb
np.save(os.path.join(OUT_DIR, "confusion_matrix.npy"), cm)
report_txt = classification_report(labels, preds, target_names=class_names, digits=4)
with open(os.path.join(OUT_DIR, "classification_report.txt"), "w", encoding="utf-8") as f:
    f.write(report_txt + "\n")

plt.figure()
plt.imshow(cm)
plt.title("Confusion Matrix")
plt.xticks(range(len(class_names)), class_names, rotation=45, ha="right")
plt.yticks(range(len(class_names)), class_names)
plt.colorbar()
plt.tight_layout()
plt.savefig(os.path.join(OUT_DIR, "confusion_matrix.png"), dpi=200)
plt.close()

"""## 11. Misclassifications

"""

mis_idx = np.where(preds != labels)[0]
print("Misclassified:", len(mis_idx), "out of", len(labels))

# Save misclassified list for eval.ipynb
import csv
with open(os.path.join(OUT_DIR, "misclassified.csv"), "w", newline="", encoding="utf-8") as f:
    w = csv.writer(f)
    w.writerow(["path","text","true","pred","true_name","pred_name"])
    for i in mis_idx:
        y = int(labels[i]); p = int(preds[i])
        w.writerow([paths[i], texts[i], y, p, class_names[y], class_names[p]])

# Save a small grid image of up to N misclassified examples (TALC/headless friendly)
N = 12
sel = mis_idx[:N]
if len(sel) > 0:
    cols = 4
    rows = int(np.ceil(len(sel) / cols))
    plt.figure(figsize=(4 * cols, 4 * rows))
    for j, i in enumerate(sel):
        img = Image.open(paths[i]).convert("RGB")
        plt.subplot(rows, cols, j + 1)
        plt.imshow(img)
        plt.axis("off")
        y = int(labels[i]); p = int(preds[i])
        plt.title(f"T:{class_names[y]} / P:{class_names[p]}")
    plt.tight_layout()
    plt.savefig(os.path.join(OUT_DIR, "misclassified_grid.png"), dpi=200)
    plt.close()

# Save history CSV (so eval.ipynb can plot curves)
save_history_csv(history, os.path.join(OUT_DIR, "history.csv"))
